package directdronedelivery.entity.enumerators;

public enum DroneStatus {
    DOCKED, CARGO_LOADING, READY_FOR_TAKE_OFF, AIRBORNE,LANDING_AT_THE_DESTINATION, RETURNING_TO_WAREHOUS,
    HOUSTON_WE_HAVE_A_PROBLEM, DURING_MAINTENANCE,
    ROUTE_UPLOADED, UPLOAD_FAILED
}
